venafi-auth-helper/Makefile
venafi-auth-helper/namespaces/jetstack-secure.yaml
venafi-auth-helper/namespaces/sandbox.yaml
venafi-auth-helper/templates/auth/cert-policy-auth.yaml
venafi-auth-helper/templates/auth/cert-policy-rbac-auth.yaml
venafi-auth-helper/templates/auth/sample-auth-cert.yaml
venafi-auth-helper/templates/auth/vauth-auth-secret.yaml
venafi-auth-helper/templates/auth/vauth-policy-secret.yaml
venafi-auth-helper/templates/auth/venafi-auth-issuer.yaml
venafi-auth-helper/templates/auth/venafi-policy-issuer.yaml
venafi-auth-helper/templates/user/cert-policy-rbac-user.yaml
venafi-auth-helper/templates/user/cert-policy-user.yaml
venafi-auth-helper/templates/user/sample-user-cert.yaml
venafi-auth-helper/templates/user/vauth-policy-secret.yaml
venafi-auth-helper/templates/user/vauth-user-secret.yaml
venafi-auth-helper/templates/user/venafi-policy-issuer.yaml
venafi-auth-helper/templates/user/venafi-user-issuer.yaml
venafi-auth-helper/vauth-helper/values.yaml

added vauth helper

---

cert-manager-ingress-nginx-eks/README.md
cert-manager-ingress-nginx-eks/addendum/README.md
cert-manager-ingress-nginx-eks/ingress.yaml.template
cert-manager-ingress-nginx-eks/issuer.yaml

Added material for new demo, using ingress-nginx with cert-manager on EKS

added cert-manager-ingress-nginx-eks demo

---

README.md
docs/11.cert-manager-samples.md

Updated header in document

---

certificate-approver/Makefile
docs/10.certs-with-venafi-enhanced-issuer.md
venafi-enhanced-issuer/Makefile

removed gs reference and updated make file

removed gs reference and updated make file

---

.gitignore
Makefile
docs/10.certs-with-venafi-enhanced-issuer.md
enterprise-cert-manager/Makefile
enterprise-cert-manager/cert-manager/approver-disabled.yaml
enterprise-cert-manager/cert-manager/approver-enabled.yaml
enterprise-cert-manager/cert-manager/restricted-seccomp.yaml
settings-template.sh
venafi-enhanced-issuer/Makefile
venafi-enhanced-issuer/templates/vault/cert-policy-and-rbac.yaml
venafi-enhanced-issuer/templates/vault/sample-cert.yaml
venafi-enhanced-issuer/templates/vault/vault-issuer-rbac.yaml
venafi-enhanced-issuer/templates/vault/vault-policy-team-1.hcl
venafi-enhanced-issuer/templates/vault/vault-policy-team-2.hcl
venafi-enhanced-issuer/templates/vault/vault-service-account.yaml
venafi-enhanced-issuer/templates/vault/vault-values.yaml
venafi-enhanced-issuer/templates/vault/vault-vtpp-enhanced-issuer.yaml
venafi-enhanced-issuer/templates/vtpp-secret-venafi-issuer.yaml

Added Venafi enhanced issuer documentation and files for integration with vault
Updated Settings.sh to add refresh token and also kubernetes host
Added scc profile for openshift

added hashicorp integration for venafi enhanced issuer

---

.gitignore
settings-template.sh

updated settings.sh

---

cert-manager-csi-spiffe/Makefile
cert-manager-csi/Makefile
cert-sync-to-venafi/Makefile
enterprise-cert-manager/cert-manager/restricted-seccomp.yaml
venafi-enhanced-issuer/Makefile

corrected paths in makefiles , updated scc profile

corrected paths in makefiles , updated scc profile

---

docs/10.certs-with-venafi-enhanced-issuer.md

Updated you tube link for enhanced issuer in docs

updated youtube link

---

settings-template.sh

Remove empty lines

---

cert-manager-opnshift-routes/Makefile
docs/11.cert-manager-samples.md
examples/Makefile
service-mesh/istio/Makefile

Updated make file, chart reference for istio and docs

updated docs and makefile references

---

certificate-approver/Makefile
certificate-approver/templates/venafi-cloud-issuer.yaml
common/templates/venafi-cloud-connection.yaml
settings-template.sh

Fix typo in venafi cloud connection.
Add TLSP Cloud connection and a target to call it.

Update version numbers for VEI, Policy approver.

---

Makefile
cert-manager-csi-spiffe/Makefile
cert-manager-csi/Makefile
certificate-approver/Makefile
docs/02.create-venafi-connection.md
docs/11.certs-with-venafi-enhanced-issuer.md
venafi-enhanced-issuer/Makefile
venafi-enhanced-issuer/templates/cert-policy-and-rbac.yaml
venafi-enhanced-issuer/templates/sample-cert.yaml
venafi-enhanced-issuer/templates/vault/cert-policy-and-rbac.yaml
venafi-enhanced-issuer/templates/vault/sample-cert-vault.yaml

Updated documentation for enhanced issuer

updated clean up scripts , and vault specs for enhanced issuer

---

docs/03.auto-approve-certs.md
docs/11.certs-with-venafi-enhanced-issuer.md
docs/13.tlsp4k8s-operator.md
settings-template.sh
tlsp4k8s-operator/Makefile
tlsp4k8s-operator/namespaces/sandbox.yaml
tlsp4k8s-operator/templates/install-cluster-addons.yaml
tlsp4k8s-operator/templates/sample-cert1.yaml
tlsp4k8s-operator/templates/sample-cert2.yaml
tlsp4k8s-operator/templates/venafi-secret.yaml

Updated TLSPK operator process and updated documentation

Updated operator readme and added files for secret cert etc.

---

projects/ven01/LICENSE
projects/ven01/Makefile
projects/ven01/README.md
projects/ven01/aws/cert-policy-and-rbac.yaml
projects/ven01/create-cluster.sh
projects/ven01/namespaces/sandbox.yaml
projects/ven01/namespaces/venafi.yaml
projects/ven01/samples/sample-aws-pca-cert.yaml
projects/ven01/samples/sample-cert.yaml
projects/ven01/templates/cloud/venafi-cloud-cluster-issuer.yaml
projects/ven01/templates/cloud/venafi-cloud-connection.yaml
projects/ven01/templates/cloud/venafi-cloud-secret.yaml
projects/ven01/templates/common/cert-policy-and-rbac.yaml
projects/ven01/templates/common/venafi-connection-rbac.yaml
projects/ven01/templates/dc/venafi-tpp-cluster-issuer.yaml
projects/ven01/templates/dc/venafi-tpp-connection.yaml
projects/ven01/templates/dc/venafi-tpp-secret.yaml
projects/ven01/templates/helm/aws-pca-issuer-irsa.yaml
projects/ven01/templates/helm/aws-pca-issuer.yaml
projects/ven01/templates/helm/cloud-vei-values.yaml
projects/ven01/templates/helm/datacenter-vei-values.yaml
projects/ven01/templates/helm/venafi-agent.yaml
projects/ven01/templates/pca/aws-pca-issuer-irsa.yaml
projects/ven01/templates/pca/aws-pca-issuer.yaml
projects/ven01/templates/pca/aws-secret.yaml
projects/ven01/templates/pca/awspca-access-policy.json
projects/ven01/vars-template.sh

Samples including Venafi Enhanced Issuer and AWS PCA

Venafi and AWS PCA demo

---

projects/ven02/LICENSE
projects/ven02/Makefile
projects/ven02/README.md
projects/ven02/create-cluster.sh
projects/ven02/namespaces/sandbox.yaml
projects/ven02/namespaces/venafi.yaml
projects/ven02/samples/sample-cert.yaml
projects/ven02/templates/common/cert-policy-and-rbac.yaml
projects/ven02/templates/common/venafi-connection-rbac.yaml
projects/ven02/templates/dc/venafi-tpp-cluster-issuer.yaml
projects/ven02/templates/dc/venafi-tpp-connection.yaml
projects/ven02/templates/dc/venafi-tpp-secret.yaml
projects/ven02/templates/dc/venafi-tpp-trust-bundle.yaml
projects/ven02/templates/helm/datacenter-vei-values.yaml
projects/ven02/vars-template.sh
projects/ven02/versions.sh

Sample project with minimum components to request certificates using VenafiClusterIssuer

Sample project with minimum components to request certificates using VenafiClusterIssuer

---

main/Makefile
main/templates/cloud/venafi-cloud-connection.yaml
main/templates/cloud/venafi-cloud-managed-public-cert.yaml
main/templates/cloud/venafi-cloud-privateca-cluster-issuer.yaml
main/templates/cloud/venafi-cloud-publicca-cluster-issuer.yaml
main/templates/dc/venafi-tpp-connection.yaml
main/templates/dc/venafi-tpp-managed-public-cert.yaml
main/templates/dc/venafi-tpp-privateca-cluster-issuer.yaml
main/templates/dc/venafi-tpp-publicca-cluster-issuer.yaml
main/templates/helm/istio-csr-values.yaml
main/templates/servicemesh/firefly-mesh-wi-issuer.yaml
samples/cert-manager-csi/Makefile
samples/cert-manager-csi/templates/redis-certs-policy-and-rbac.yaml
samples/cert-manager-csi/templates/redis-client.yaml
samples/cert-manager-csi/templates/redis-server.yaml
scripts/Makefile

Update issuer config to simplify names

---

main/samples/05-phantom-ca-cert.yaml
main/templates/certs/02-expiry-eddie-cert.yaml
main/templates/certs/04-ghost-rider-cert.yaml

Change cert duration for sample certs

---

main/templates/common/cert-policy-and-rbac.yaml

Add wildcard to namespace selector

---

projects/aks-istio/Makefile
projects/aks-istio/README.md
projects/aks-istio/namespaces/aks-mesh-apps.yaml
projects/aks-istio/templates/helm/aks-istio-csr-values.yaml

experimental - aks istio addon

---

main/templates/helm/venafi-agent.yaml
samples/openshift/venafi-scc.yaml

Fix agent service account. Set it to true

---

.gitignore
README.md
projects/cert-discovery/Makefile
projects/cert-discovery/README.md
projects/cert-discovery/create-cluster.sh
projects/cert-discovery/namespaces/venafi.yaml
projects/cert-discovery/templates/helm/venafi-agent.yaml
projects/cert-discovery/vars-template.sh
projects/ven03/Makefile
projects/ven03/README.md
projects/ven03/create-cluster.sh
projects/ven03/namespaces/sandbox.yaml
projects/ven03/samples/sample-cert.yaml
projects/ven03/samples/sample-firefly-certificates.yaml
projects/ven03/templates/cloud/venafi-cloud-connection.yaml
projects/ven03/templates/cloud/venafi-cloud-privateca-cluster-issuer.yaml
projects/ven03/templates/cloud/venafi-cloud-secret.yaml
projects/ven03/templates/common/cert-policy-and-rbac.yaml
projects/ven03/templates/common/venafi-connection-rbac.yaml
projects/ven03/templates/helm/cloud-vei-values.yaml
projects/ven03/vars-template.sh
projects/ven03/versions.sh

Additonal usecases for discovery and venafi components in a cluster with existing cert-manager

---

main/Makefile
main/create-cluster.sh
main/versions.sh
projects/ven01/Makefile
projects/ven02/Makefile
samples/ingress/Makefile
samples/ingress/templates/sample-ingress.yaml

Update CLI (based on venctl 1.9.0), add a sample ingress and also updating versions to match venctl print-versions

---

projects/cert-discovery/sample/agent-install.sh
projects/cert-discovery/sample/create-cluster.sh
projects/cert-discovery/sample/helm/venafi-agent.yaml

Add sample discovery with helm (wip)
